services:
  - type: web
    name: nextjs-app
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    env: node
    nodeVersion: 18.17.0  # Add this line
    envVars:
      - key: NODE_ENV
        value: production